### ISSUE TITLE
Sharing improvements

### ISSUE THREAD

**Issue by aienabled** [Noesis/Xamltoy#2]
Hi guys,
nothing on the XamlToy page suggests that I can use Gists to share my creation.

It would be great if you add at least some notice about that (e.g. a Share button with a popup explanation how to use the feature).

It would be best if you can utilize Gists API (through `POST /gists`, IIRC it requires OAuth) to quickly save a gist right from the XamlToy.

Regards!

**Comment by s-fernandez-v** [comment]
We have links for "Help" and "Send feedback" at the bottom of the page, but maybe they are not visible enough. We can probably add some icons that make that stand out a bit more, what do you think?

![image](https://user-images.githubusercontent.com/9131989/100851791-f0317580-3485-11eb-8207-75d4661430fe.png)


We thought about the possiblity to save the work directly from Xamltoy but ended up having things simpler from our side, specifically to avoid dealing with authentication hassle, at least in the initial version. We'll think about it for the future.

**Comment by aienabled** [comment]
The help button doesn't suggest there is a sharing capability.

It would be best to have a Share button (maybe near the Run button and with a similar style).
For now, you can make that it doesn't share anything but displays a popup with a short manual like this one:
```
You can share your creation by saving it as a gist!
1. Open https://gist.github.com/ 
2. Copy your XAML code there
3. Enter into the Filename field: "Main.xaml"
4. Press "Create public gist"
5. Append the gist ID to XamlToy URL
For example, to view gist.github.com/2e4fb7d5143b4505992b33fec34d0592 in XamlToy, use the URL www.noesisengine.com/xamltoy/2e4fb7d5143b4505992b33fec34d0592
Additionally, you can store dependent resources and assets in separate gist files.
Read more... (link to https://github.com/Noesis/Xamltoy#sharing-guide)
```

Regards!

**Comment by s-fernandez-v** [comment]
Fixed by adding an explicity SHARE button on the top right navigation bar.
Thanks a lot for the feedback.
